version: "1"

services:
  backend-user-management:
    build: .
    volumes:
      - ./:/code
    working_dir: /code/app
    command: uvicorn main:app --host 0.0.0.0 --reload --port 8001
    ports:
      - "8001:8001"
    expose:
      - "8001"
    networks:
      - microservice-network

networks:
  microservice-network:
    external: true
