# This workflow run tests of user management service

name: Runs tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - release

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Creating environment file
        run: cp example.env .env

      - name: Start containers
        run: docker-compose up -d --build

      - name: Waiting until db structure is created
        run: sleep 5

      - name: Installing dependencies
        run: sudo apt-get install -y python3 python3-pip && pip3 install -r requirements.txt

      - name: Creating data for tests
        run: python3 helper_scripts/create_data.py

      - name: Run tests
        run: docker-compose run backend-user-management bash -c "pytest -v"

      - name: Stop containers
        if: always()
        run: docker-compose down
